name: MeowCraft
main: cn.miranda.MeowCraft.MeowCraft
version: 0.0.9
author: Miranda
description: 猫子的魔法插件
softdepend: [ProtocolLib, Vault, mcMMO]
load: POSTWORLD
api-version: 1.15

commands:
  hpset:
    description: 设置血量上限模块
    usage: /hpset [player] <value>
    permissions: hpset.set
  meowcraft:
    description: 核心模块
    usage: /meowcraft <help|reload>
    permissions: meow.admin
  convertexp:
    description: 互转经验和金钱模块
    usage: /convertexp <tomoney|toexp> <exp|money> <money|exp>
    permissions: meowcraft.convert
  imprint:
    description: 烙印卷轴模块
    usage: /imprint [player] <amount>
    permissions: imprint.admin
  deadcost:
    description: 死亡惩罚模块
    usage: /deadcost [value]
    permissions: deadcost.admin
  flytime:
    description: 限时飞行模块
    usage: /flytime <player> <time>
    permissions: flytime.admin
  occ:
    description: 职业模块
    usage: /occ <on|off|reset>
    permissions: occ.*
  occskill:
    description: 职业技能模块
    usage: /occskill <list|cooldown>
    permissions: occ.*
  esotericascroll:
    description: 职业技能模块
    usage: /esotericascroll <player> <skill>
    permissions: esotericascroll.admin
  cmdlogger:
    description: 命令监视模块
    usage: /cmdlogger <player> <on|off>
    permissions: cmdlogger.admin
  bank:
    description: 银行模块
    usage: /bank
    permissions: bank.admin