name: MeowCraft
main: cn.miranda.MeowCraft.MeowCraft
version: 0.5.7
author: Miranda
description: 猫子的魔法插件
softdepend: [ Vault, mcMMO, PermissionsEx, Citizens, LibsDisguises ]
load: POSTWORLD
api-version: 1.15

commands:
  hpset:
    description: 设置血量上限模块
    usage: /hpset [player] <value>
    permissions: hpset.set
  meowcraft:
    description: 核心模块
    usage: /meowcraft <help|reload|save|debug>
    permissions: meow.admin
  convertexp:
    description: 互转经验和金钱模块
    usage: /convertexp <tomoney|toexp> <exp|money> <money|exp>
    permissions: convert.admin
  imprint:
    description: 烙印卷轴模块
    usage: /imprint [player] <amount>
    permissions: imprint.admin
  deadcost:
    description: 死亡惩罚模块
    usage: /deadcost [value]
    permissions: deadcost.admin
  flytime:
    description: 限时飞行模块
    usage: /flytime <set|check|abort> <player> <time>
    permissions: flytime.admin
  occ:
    description: 职业模块
    usage: /occ <on|off|reset>
    permissions: occ.*
  occskill:
    description: 职业技能模块
    usage: /occskill <list|cooldown>
    permissions: occ.*
  esotericascroll:
    description: 职业技能模块
    usage: /esotericascroll <player> <skill>
    permissions: esotericascroll.admin
  cmdlogger:
    description: 命令监视模块
    usage: /cmdlogger <player> <on|off>
    permissions: cmdlogger.admin
  bank:
    description: 银行模块
    usage: /bank
    permissions: bank.admin
  tabping:
    description: 延迟显示模块
    usage: /tabping
    permissions: tabping.admin
  townapply:
    description: 加入小镇申请
    usage: /townapply <town>
    permissions: townapply.use
  townadmin:
    description: 镇长审核
    usage: /townadmin <list|apply|deny> <player>
    permissions: town.admin
  playerstatus:
    description: 存储或取出玩家的状态
    usage: /playerstatus <setdefault|setrestore>
    permissions: playerstatus.admin
  strike:
    description: 用闪电移除所有攻击性生物
    usage: /strike [radius]
    permissions: strike.admin
  incomeaccount:
    description: 修改小镇公共账户
    usage: /incomeaccount <town> <check|give|take|set> [value]
    permissions: incomeaccount.admin
  trade:
    description: NPC 交易面板设置
    usage: /trade <NpcID> <create|delete|set> <slot> <price>
    permissions: trade.admin
  monstercard:
    description: 怪物卡片模块
    usage: /monstercard [player] <amount>
    permissions: monstercard.admin